title:              Igor Loncarevic
email:              igor@loncarevic.net
description:        Portfolio & Blog
author:             Igor Loncarevic
baseurl:            ""
url:                "https://www.loncarevic.net"

# Social Profiles
github_username:    cookie-cutter-123
linkedin_username:  igor-loncarevic-000b0b141/


# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: StartBootstrap/startbootstrap-clean-blog-jekyll
